### ISSUE TITLE
 patchwork++ has more poor segmentation than patchwork

### ISSUE THREAD

**Issue by WangY69** [url-kaist/patchwork-plusplus-ros#13]
Thank you for contribution! 
When I run this project, I found that patchwork ground segmentation is better than patchwork++(on kitti_0_sample. bag), which seems to be different from what is claimed in the paper. Why? Both use default parameters.

![image](https://user-images.githubusercontent.com/53323745/222337336-f0f9ece5-81ad-408c-b955-3c7f734c77a9.png)

Similar to the poor segmentation of patchwork++ in the figure above, there are many cases.

**Comment by seungjae24** [comment]
Hi, @WangY69. Thank you for sharing the above result.

Actually, this result seems to be related to noisy points under the cars due to the reflection. As I stated in the paper, I tried to remove these noises using their geometrical properties and intensity information. However, unfortunately, the assumption does not hold always for every noise point. I think it needs some improvement for removing outliers more precisely. By the way, I can recommend you to increase the threshold value of the point intensity (RNR_intensity_thr in config/params.yaml  file) up to 0.5 ~ 0.6 to remove points more aggresively. It might help you to erase noisy points under ground resulting better ground segmentation. Thank you.
